Milestone 1: Plain Javascript with objects
alvarorf/awesomebooks-js pull request #1
Opened 2022-02-08 22:41 UTC by alvarorf

In this milestone, the following features are added:
- Create a collection that keeps a list of books.
- Create a function to add a new book to the collection, with title and author.
- Create a function to remove a book from the collection.
- Display all books saved in the collection in the top part of the page.
- It makes sure that when a user clicks the "Add" button: i.  A new book is added to the collection. ii.  The new book is displayed in the page.
- It makes sure that when a user clicks the "Remove" button:
    The correct book is removed from the collection.
    The correct book dissapears from the page.

- Data is preserved in the browser's memory by using localStorage.

Thank you for your comments.

2022-02-08 23:07 UTC, mateo951 requested changes
### Hi Team, 

📝👌 **Your project highlights** 🔥😎 
- Github Flow, and PR as expected ✔
- JS Best Practices ✔
- The functionality of the app works perfectly 🙌

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-08 23:07 UTC, mateo951 commented on index.js
> +const retrieveBooks = () => JSON.parse(localStorage.getItem('books'));
Fantastic work 💪 You are using an array of objects for keeping the list of books 📝

2022-02-08 23:07 UTC, mateo951 commented on index.js
> +};
Add and remove book functions are working as a charm 🔥😎🔥

2022-02-09 14:57 UTC, alvarorf commented on index.html
> +</body>
Thank you!

2022-02-09 14:58 UTC, alvarorf commented on index.js
> +const renderBooks = () => {
Thanks!

2022-02-10 20:54 UTC, merged