Milestone 2: Refactor to use Javascript classes
alvarorf/awesomebooks-js pull request #2
Opened 2022-02-10 21:01 UTC by alvarorf

In this milestone, the following features have been added:
- Any objects or arrays are used inside classes.
- A class called 'Methods' has been created, which contains the methods to add and remove books, among others.
- The original functionality of the application has been maintained, while introducing no bugs (that we have noticed).
- Only plain JavaScript is used.
- CSS styles to the application have been added to match the given wireframe.

Thank you for your comments.

2022-02-10 22:44 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @alvarorf + @joshuaivie  👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct Github Flow.
✅ Used JavaScript classes and methods.
✅ App works as expected

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 22:44 UTC, Cathella commented on index.js
> +/* eslint-disable no-unused-vars */
Hello @team, you are doing a good job in this milestone 💪🏻! However, You need to make a few changes

- [ ] Disabling linters is not a good development practice because linters helps you write good quality code.  Please kindly remove this line add instead fix the linter.

2022-02-10 22:44 UTC, Cathella commented on index.js
> +  };
Good job using this condition 👍🏻

2022-02-10 22:44 UTC, Cathella commented on index.js
>  /* eslint-enable no-unused-vars */
- [ ] Kindly remove this line and fix the linters as explain above ☝🏻

2022-02-10 22:44 UTC, Cathella commented on styles.css
> +  /* stylelint-enable */
- [ ] Please enable the linters as explained above ☝🏻

2022-02-11 00:22 UTC, brytebee approved these changes
Hi Team👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 00:37 UTC, merged